{% set name = "dionysus" %}
{% set version = "2.1.4" %}
{% set sha256 = "4284467228f3b0a577a387ee5c8a7dccf12a4ca0ce70d79f0f7443e6afacba5d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libboost-headers
    - scikit-build-core
    - pybind11
    - zlib
  run:
    - python
    - intervaltree >=3.1.0 # new
    - sortedcontainers >=2.4.0 # new

test:
  imports:
    - dionysus
    - intervaltree

about:
  home: https://mrzv.org/software/dionysus2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for computing persistent homology
  doc_url: https://mrzv.org/software/dionysus2
  dev_url: https://github.com/mrzv/dionysus

extra:
  recipe-maintainers:
    - mrzv
