{% set name = "dionysus" %}
{% set version = "2.1.1" %}
{% set sha256 = "ae19ba4f212389df269a03be080891cd716a7eff0f19473b967a7f60a4ba7924" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libboost-headers
    - setuptools
  run:
    - python
    - intervaltree >=3.1.0 # new
    - sortedcontainers >=2.4.0 # new

test:
  imports:
    - dionysus
    - intervaltree

about:
  home: https://mrzv.org/software/dionysus2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for computing persistent homology
  doc_url: https://mrzv.org/software/dionysus2
  dev_url: https://github.com/mrzv/dionysus

extra:
  recipe-maintainers:
    - mrzv
