{% set name = "dionysus" %}
{% set version = "2.0.3" %}
{% set sha256 = "cdd44b3dfd7199290f28af1b6d3fdd61167db231601330a9b73cad083a86366d" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  script: >
    CC=clang CXX=clang++ CXXFLAGS="${CXXFLAGS} -stdlib=libc++" LDFLAGS="${LDFLAGS} -lc++abi"  # [linux]
    python setup.py install --single-version-externally-managed --record record.txt
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - clangdev  # [linux]
    - libcxx    # [linux]
    - cmake
    - boost-cpp
  run:
    - python
    - libcxx    # [linux]

test:
  imports:
    - dionysus

about:
  home: http://mrzv.org/software/dionysus2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library for computing persistent homology
  doc_url: http://mrzv.org/software/dionysus2
  dev_url: https://github.com/mrzv/dionysus

extra:
  recipe-maintainers:
    - mrzv
