appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Py/Huut1+INFhdfArTC/nRFt1RFIs+07GABp4U9RZ0DBIbVKW8FKdrpxpoao+Bwic/FGupbMB5jYMHLLQZcujryyiCZcoaSfYpaAhW4q1cjtLpzgwWk9Z2KGG6Qq+gkc+biM5KKQv9ON+89UqCSXMyn4fmPk2ud3hTw77BIjCFCf5Mu1h2rbRZL52k6ojoJ0PXkG8BP4fGb1gB0gsvhGmHup2LksyY2AxDwrJXWctM+IB8P2Exjapgy44GKgvDC6F4PFT2YEnRdIw+vSsd7sej/+sKV5R/8lSEClrlhM4JS4JJ3U1KijqdYn56Z8sR4jIwe8tPzpiQHHPWlDxss7Q/TIm7b9c9FJ+k6oOdhdy+wGMGYVbfJPX7ptw8E8Dsuqwdf/jfMDy2dHi3i1Rq0lhjC8FbgQpQ7nNSVJA5iCSrriqAYrqBOvsqw8pGPM5aAC3qMgusALj5c+lhDiKUM0BHqYycTRP5/WL5R12MkvzOuBh/OezIqaxYjf/fOnpMJNySZdK0DXBkK8KA2/ClD7Wa7UaTLsoFUMo9Zjf40LJXZMlJB8ULKdI6p25ytd3/ipCOcWCbMwsEkWwU4aI2Y880fTCiGfZ+sUuymKaB8V0MZV7pj5y7Tqe2QEM4q4bhlxBZLSxRst5DZ9o21SveuM3c5Z80XA7jvwafsi2Qp7Jn8=}
